CREATE TABLE `question` (
	`questionid` INT NOT NULL AUTO_INCREMENT,
	`questiontitle` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`questioncontent` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`questiondate` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP),
	`questionfixdate` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	`ischecked` TINYINT NULL DEFAULT NULL,
	`imagepath` VARCHAR(2048) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`userid` VARCHAR(32) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`questionid`) USING BTREE,
	INDEX `userid` (`userid`) USING BTREE,
	CONSTRAINT `question_ibfk_1` FOREIGN KEY (`userid`) REFERENCES `recipeuser` (`userid`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=30
;
